### ISSUE TITLE
Get-DismalLockScreen

### ISSUE THREAD

**Issue by JAProvencher** [stibinator/GreatDismal#1]
In the last two versions published to PowerShell Gallery, Get-DismalLockScreen doesn't exist.  Also, when I import the module, nothing is available:

get-module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.0.10     greatdismal

Sorry for the formatting.

If I explicitly import greatdismal.psm1, it works.  Because of this, the scheduled task doesn't work, where there wasn't a problem in the older versions.

**Comment by stibinator** [comment]
The name of the command has changed, I made it more powershell-y. It's `get-Despair` now. So you install with `get-despair -install`

**Comment by stibinator** [comment]
I'm surprised that anyone else is actually using it. Let me know if you have any other problems

**Comment by JAProvencher** [comment]
I like the random pictures.

If I run the scheduled task manually, it stays running.  The pictures aren’t changing after unlocking.  And like I said in the comment, Get-Despair doesn’t work unless I import the .psm1 file explicitly. When I use “import-module greatdismal”, “get-module greatdismal” doesn’t show any exported functions.

I’ve never built a module, but PowerShell is my job. Unless you have something, I’ll pass it and maybe version 1.0.8 through WinMerge to see if anything sticks out.

Cheers,

J. Provencher

**Comment by JAProvencher** [comment]
Hey mate,

I updated today and it’s working great.  I need to look through some of the stuff you do so may e I can add some snippets to my repertoire.

I have a blog I haven’t done an update on in a while but I’ll put a shoutout to you there.  (HTTPS:MyITRamblings.blogspot.com).

**Comment by stibinator** [comment]
No worries. I was going to suggest you do `update-module greatDismal` but it looks like you beat me to it.
